In [1]:
import tensorflow as tf    # tensorflow를 import하고, 이름을 tf로 지정 
import numpy as np    # numpy를 import하고, 이름을 np로 지정

tf.enable_eager_execution()    # 즉시 실행(Eager Execution) 모드로 변경(그래프 기반 모드에서 즉시 실행 모드로 변경)
tf.__version__   # tensorflow version check

'1.13.1'

In [2]:
tf.set_random_seed(0)  # 그래프 level의 난수 seed를 설정

In [3]:
x1_data = [1, 0, 3, 0, 5]    # x1_data(feature1) 정의
x2_data = [0, 2, 0, 4, 0]    # x2_data(feature2) 정의
y_data  = [1, 2, 3, 4, 5]    # y_data 정의

W1 = tf.Variable(tf.random_uniform([1], -10.0, 10.0))    # 정규분포를 따르는 random number
                                                         # (shape=(1,))를 생성, W1이 참조
W2 = tf.Variable(tf.random_uniform([1], -10.0, 10.0))    # 정규분포를 따르는 random number
                                                         # (shape=(1,))를 생성, W2가 참조
b  = tf.Variable(tf.random_uniform([1], -10.0, 10.0))    # 정규분포를 따르는 random number
                                                         # (shape=(1,))를 생성, b가 참조

learning_rate = tf.Variable(0.001)    # learning_rate를 0.001로 설정 (해당 데이터를 갖는 노드를 참조)

for i in range(1000+1):    # 1001회 시행
    with tf.GradientTape() as tape:    
                            # with 범위 내 variable들의 변화를 tape에 기록 (여기서는 W1, W2, b가 해당)
        hypothesis = W1 * x1_data + W2 * x2_data + b
                            # hypothesis(가설)을 정의 : W1(weight1) * x1_data + W2(weight2) * x2_data + b(bias)
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))    
                            # cost function 정의 : (1/m) * ∑(i=1~m) (hypothesis-y)^2
    W1_grad, W2_grad, b_grad = tape.gradient(cost, [W1, W2, b])    
                            # gradient 함수가 cost function을 W1, W2, b에 대하여 미분한 값을 tuple
                            # 형태로 반환, 반환된 값을 W1_grad, W2_grad, b_grad가 참조
                            # tape.gradient(GradientTape.gradient) 호출 직후,
                            # tape(GradientTape)에 포함된 리소스는 해제됨
    W1.assign_sub(learning_rate * W1_grad)    # W1 = W1 - learning_rate(=0.001) * W1_grad
    W2.assign_sub(learning_rate * W2_grad)    # W2 = W2 - learning_rate(=0.001) * W2_grad
    b.assign_sub(learning_rate * b_grad)    # b = b - learning_rate(=0.001) * b_grad

    if i % 50 == 0:    # 50회마다
        # i 값(step), cost function 값, W1(weight1) 값, W2(weight2) 값, b(bias) 값 출력 
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.6f}".format(
          i, cost.numpy(), W1.numpy()[0], W2.numpy()[0], b.numpy()[0]))

Instructions for updating:
Colocations handled automatically by placer.
    0 | 335.280823 |    -4.0663 |     1.1220 |  -6.065215
   50 |  76.037262 |    -0.8001 |     1.6209 |  -4.978779
  100 |  18.959263 |     0.7151 |     1.8781 |  -4.429109
  150 |   6.310240 |     1.4125 |     2.0104 |  -4.134423
  200 |   3.445082 |     1.7284 |     2.0768 |  -3.961648
  250 |   2.743659 |     1.8667 |     2.1075 |  -3.847750
  300 |   2.525401 |     1.9225 |     2.1184 |  -3.762738
  350 |   2.417754 |     1.9402 |     2.1181 |  -3.692262
  400 |   2.337300 |     1.9403 |     2.1114 |  -3.629400
  450 |   2.264998 |     1.9325 |     2.1008 |  -3.570778
  500 |   2.196328 |     1.9213 |     2.0881 |  -3.514729
  550 |   2.130126 |     1.9085 |     2.0741 |  -3.460409
  600 |   2.066037 |     1.8953 |     2.0595 |  -3.407385
  650 |   2.003917 |     1.8819 |     2.0444 |  -3.355424
  700 |   1.943679 |     1.8686 |     2.0293 |  -3.304398
  750 |   1.885258 |     1.8555 |     2.0141 |  -3.254230


In [4]:
# x_data, y_data 정의
x_data = [
    [1., 0., 3., 0., 5.],
    [0., 2., 0., 4., 0.]
]
y_data  = [1, 2, 3, 4, 5]

W = tf.Variable(tf.random_uniform([1, 2], -1.0, 1.0))    # 정규분포를 따르는 random number
                                                         # (shape=(1, 2))를 생성, W가 참조
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))    # 정규분포를 따르는 random number
                                                      # (shape=(1,))를 생성, b가 참조
    
learning_rate = tf.Variable(0.001)    # learning_rate를 0.001로 설정 (해당 데이터를 갖는 노드를 참조)

for i in range(1000+1):    # 1001회 시행
    with tf.GradientTape() as tape:    # with 범위 내 variable들의 변화를 tape에 기록 (여기서는 W, b가 해당)
        hypothesis = tf.matmul(W, x_data) + b    # (1, 2) * (2, 5) = (1, 5)
                                        # hypothesis(가설)을 정의 : W(weight) * x_data + b(bias)
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))    
                                        # cost function 정의 : (1/m) * ∑(i=1~m) (hypothesis-y_data)^2

        W_grad, b_grad = tape.gradient(cost, [W, b])    
                                        # gradient 함수가 cost function을 W, b에 대하여 미분한 값을 tuple
                                        # 형태로 반환, 반환된 값을 W_grad, b_grad가 참조
                                        # tape.gradient(GradientTape.gradient) 호출 직후,
                                        # tape(GradientTape)에 포함된 리소스는 해제됨            
        W.assign_sub(learning_rate * W_grad)    # W = W - learning_rate(=0.001) * W_grad
        b.assign_sub(learning_rate * b_grad)    # b = b - learning_rate(=0.001) * b_grad
    
    if i % 50 == 0:    # 50회마다
        # i 값(step), cost function 값, W[0][0](weight1) 값, W[0][1](weight2) 값, b(bias) 값 출력 
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.6f}".format(
            i, cost.numpy(), W.numpy()[0][0], W.numpy()[0][1], b.numpy()[0]))

    0 |  36.403778 |    -0.6231 |    -0.3508 |  -0.961774
   50 |   9.372901 |     0.2914 |     0.1682 |  -0.557764
  100 |   2.639858 |     0.7060 |     0.4867 |  -0.347756
  150 |   0.825069 |     0.8912 |     0.6846 |  -0.235665
  200 |   0.284990 |     0.9721 |     0.8088 |  -0.174012
  250 |   0.106844 |     1.0062 |     0.8873 |  -0.138953
  300 |   0.042677 |     1.0195 |     0.9372 |  -0.118279
  350 |   0.018044 |     1.0241 |     0.9690 |  -0.105598
  400 |   0.008188 |     1.0250 |     0.9893 |  -0.097477
  450 |   0.004138 |     1.0246 |     1.0022 |  -0.092026
  500 |   0.002439 |     1.0239 |     1.0104 |  -0.088173
  550 |   0.001710 |     1.0230 |     1.0156 |  -0.085299
  600 |   0.001384 |     1.0223 |     1.0188 |  -0.083036
  650 |   0.001227 |     1.0217 |     1.0207 |  -0.081161
  700 |   0.001142 |     1.0212 |     1.0218 |  -0.079538
  750 |   0.001088 |     1.0207 |     1.0224 |  -0.078080
  800 |   0.001046 |     1.0203 |     1.0227 |  -0.076735
  850 |   0.00

In [5]:
# 앞의 코드에서 bias(b)를 행렬에 추가
x_data = [
    [1., 1., 1., 1., 1.], # bias(b)
    [1., 0., 3., 0., 5.], 
    [0., 2., 0., 4., 0.]
]
y_data  = [1, 2, 3, 4, 5]

W = tf.Variable(tf.random_uniform([1, 3], -1.0, 1.0)) # [1, 3]으로 변경하고, b 삭제

learning_rate = 0.001    # learning_rate를 0.001로 설정
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
                            # GradientDescentOptimizer class는 Gradient Descent Algorithm을 구현하는
                            # 최적화 도구. class의 constructor(생성자)는 
                            # 새로운 gradient descent optimizer를 생성
for i in range(1000+1):    # 1001회 시행
    with tf.GradientTape() as tape:    # with 범위 내 variable들의 변화를 tape에 기록 (여기서는 W가 해당)
        hypothesis = tf.matmul(W, x_data)    # hypothesis(가설)을 정의 : W(weight) * x_data
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))
                                            # cost function 정의 : (1/m) * ∑(i=1~m) (hypothesis-y_data)^2
    grads = tape.gradient(cost, [W])    # gradient 함수가 cost function을 W에 대하여 미분한 값을 반환
                                        # 반환된 값을 grads가 참조
                                        # W가 shape : (1, 3)이므로 grads 또한 shape: (1, 3)
                                        # tape.gradient(GradientTape.gradient) 호출 직후,
                                        # tape(GradientTape)에 포함된 리소스는 해제됨   
    optimizer.apply_gradients(grads_and_vars=zip(grads,[W]))    
                                        # python 내장 함수 zip은 동일한 개수로 이루어진 자료형을 묶어주는 함수
                                        # grads와 W를 묶고, 이를 grads_and_vars가 참조
                                        # GradientDescentOptimizer class에 정의된 method apply_gradients는
                                        # gradient descent를 적용하여, W 값을 조정
    if i % 50 == 0:    # 50회마다
        # i 값(step), cost function 값, W[0][0](weight1) 값, W[0][1](weight2) 값, W[0][2](weight3) 값 출력
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.4f}".format(
            i, cost.numpy(), W.numpy()[0][0], W.numpy()[0][1], W.numpy()[0][2]))

    0 |  16.019751 |    -0.1985 |     0.3424 |    -0.6835
   50 |   5.635924 |     0.0582 |     0.6809 |    -0.1215
  100 |   2.141112 |     0.1997 |     0.8238 |     0.2356
  150 |   0.862825 |     0.2786 |     0.8808 |     0.4641
  200 |   0.367090 |     0.3227 |     0.9015 |     0.6112
  250 |   0.167513 |     0.3468 |     0.9074 |     0.7064
  300 |   0.085210 |     0.3593 |     0.9082 |     0.7684
  350 |   0.050615 |     0.3649 |     0.9074 |     0.8090
  400 |   0.035731 |     0.3663 |     0.9067 |     0.8359
  450 |   0.029064 |     0.3651 |     0.9063 |     0.8539
  500 |   0.025846 |     0.3624 |     0.9064 |     0.8661
  550 |   0.024085 |     0.3587 |     0.9069 |     0.8746
  600 |   0.022948 |     0.3544 |     0.9076 |     0.8807
  650 |   0.022085 |     0.3497 |     0.9086 |     0.8852
  700 |   0.021348 |     0.3449 |     0.9097 |     0.8887
  750 |   0.020676 |     0.3400 |     0.9109 |     0.8916
  800 |   0.020042 |     0.3350 |     0.9121 |     0.8940
  850 |   0.01

In [6]:
# Multi-variable linear regression (1)
X = tf.constant([[1., 2.], 
                 [3., 4.]])
y = tf.constant([[1.5], [3.5]])

W = tf.Variable(tf.random_normal([2, 1]))    # 정규분포를 따르는 random number
                                             # (shape=(2, 1))를 생성, W가 참조 
b = tf.Variable(tf.random_normal([1]))    # 정규분포를 따르는 random number
                                          # (shape=(1,))를 생성, b가 참조 

# Create an optimizer
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
                                            # GradientDescentOptimizer class는 Gradient Descent Algorithm을
                                            # 구현하는 최적화 도구. class의 constructor(생성자)는 
                                            # 새로운 gradient descent optimizer를 생성
n_epoch = 1000+1    # 시행 횟수 정의
print("epoch | cost")    # step | cost
for i in range(n_epoch):    # 1001회 시행
    # Use tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:    # with 범위 내 variable들의 변화를 tape에 기록 (여기서는 W, b가 해당)
        y_pred = tf.matmul(X, W) + b    # # y_pred(hypothesis) 정의 : XW + b
        cost = tf.reduce_mean(tf.square(y_pred - y))    # cost function 정의 : (1/m) * ∑(i=1~m) (y_pred-y)^2

    # calculates the gradients of the loss
    grads = tape.gradient(cost, [W, b])    
                    # gradient 함수가 cost function을 W, b에 대하여 미분한 값을 반환. 반환된 값을 grads가 참조
                    # grads[0]은 W에 대해 미분한 값, grads[1]은 b에 대해 미분한 값
                    # tape.gradient(GradientTape.gradient) 호출 직후,
                    # tape(GradientTape)에 포함된 리소스는 해제됨
    # updates parameters (W and b)
    optimizer.apply_gradients(grads_and_vars=zip(grads, [W, b]))
                    # python 내장 함수 zip은 동일한 개수로 이루어진 자료형을 묶어주는 함수
                    # grads와 [W, b]를 묶고, 이를 grads_and_vars가 참조
                    # GradientDescentOptimizer class에 정의된 method apply_gradients는
                    # gradient descent를 적용하여, W, b 값을 조정
    if i % 50 == 0:    # 50회마다
        # i 값(step), cost function 값 출력
        print("{:5} | {:10.6f}".format(i, cost.numpy()))

epoch | cost
    0 |  21.726822
   50 |   0.258689
  100 |   0.176868
  150 |   0.120926
  200 |   0.082678
  250 |   0.056528
  300 |   0.038649
  350 |   0.026424
  400 |   0.018067
  450 |   0.012352
  500 |   0.008445
  550 |   0.005774
  600 |   0.003948
  650 |   0.002699
  700 |   0.001845
  750 |   0.001262
  800 |   0.000863
  850 |   0.000590
  900 |   0.000403
  950 |   0.000276
 1000 |   0.000189


In [7]:
tf.set_random_seed(0)  # 그래프 level의 난수 seed를 설정

In [8]:
# data and label
x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.]

# weights
w1 = tf.Variable(10.)
w2 = tf.Variable(10.)
w3 = tf.Variable(10.)
b  = tf.Variable(10.)

learning_rate = 0.000001    # learning_rate를 0.000001로 설정

for i in range(1000+1):    # 1001회 시행
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:    # with 범위 내 variable들의 변화를 tape에 기록
                                       # (여기서는 w1, w2, w3, b가 해당)
        hypothesis = w1 * x1 +  w2 * x2 + w3 * x3 + b
                                       # hypothesis(가설)을 정의 : w1 * x1 +  w2 * x2 + w3 * x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
                                       # cost function 정의 : (1/m) * ∑(i=1~m) (hypothesis-Y)^2
    # calculates the gradients of the cost
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
                                # gradient 함수가 cost function을 w1, w2, w3, b에 대하여
                                # 미분한 값을 tuple 형태로 반환, 반환된 값을 w1_grad, w2_grad, w3_grad, b_grad가
                                # 참조. tape.gradient(GradientTape.gradient) 호출 직후,
                                # tape(GradientTape)에 포함된 리소스는 해제됨
    # update w1,w2,w3 and b
    w1.assign_sub(learning_rate * w1_grad)    # w1 = w1 - learning_rate(=0.000001) * w1_grad
    w2.assign_sub(learning_rate * w2_grad)    # w2 = w2 - learning_rate(=0.000001) * w2_grad
    w3.assign_sub(learning_rate * w3_grad)    # w3 = w3 - learning_rate(=0.000001) * w3_grad
    b.assign_sub(learning_rate * b_grad)    # b = b - learning_rate(=0.000001) * b_grad

    if i % 50 == 0:    # 50회마다
        # i 값(step), cost function 값 출력
        print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 | 5793889.5000
   50 |   64291.1562
  100 |     715.2903
  150 |       9.8461
  200 |       2.0152
  250 |       1.9252
  300 |       1.9210
  350 |       1.9177
  400 |       1.9145
  450 |       1.9114
  500 |       1.9081
  550 |       1.9050
  600 |       1.9018
  650 |       1.8986
  700 |       1.8955
  750 |       1.8923
  800 |       1.8892
  850 |       1.8861
  900 |       1.8829
  950 |       1.8798
 1000 |       1.8767


In [9]:
# data and label
x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.]

# random weights
w1 = tf.Variable(tf.random_normal([1]))
w2 = tf.Variable(tf.random_normal([1]))
w3 = tf.Variable(tf.random_normal([1]))
b  = tf.Variable(tf.random_normal([1]))

learning_rate = 0.000001    # learning_rate를 0.000001로 설정

for i in range(1000+1):    # 1001회 시행
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:    
                    # with 범위 내 variable들의 변화를 tape에 기록 (여기서는 w1, w2, w3, b가 해당)
        hypothesis = w1 * x1 +  w2 * x2 + w3 * x3 + b
                    # hypothesis(가설)을 정의 : w1 * x1 +  w2 * x2 + w3 * x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
                    # cost function 정의 : (1/m) * ∑(i=1~m) (hypothesis-Y)^2
    # calculates the gradients of the cost
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
                            # gradient 함수가 cost function을 w1, w2, w3, b에 대하여
                            # 미분한 값을 tuple 형태로 반환, 반환된 값을 w1_grad, w2_grad, w3_grad, b_grad가
                            # 참조. tape.gradient(GradientTape.gradient) 호출 직후,
                            # tape(GradientTape)에 포함된 리소스는 해제됨    
    # update w1,w2,w3 and b
    w1.assign_sub(learning_rate * w1_grad)    # w1 = w1 - learning_rate(=0.000001) * w1_grad
    w2.assign_sub(learning_rate * w2_grad)    # w2 = w2 - learning_rate(=0.000001) * w2_grad
    w3.assign_sub(learning_rate * w3_grad)    # w3 = w3 - learning_rate(=0.000001) * w3_grad
    b.assign_sub(learning_rate * b_grad)    # b = b - learning_rate(=0.000001) * b_grad

    if i % 50 == 0:    # 50회마다
        # i 값(step), cost function 값 출력
        print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 |   11325.9121
   50 |     135.3618
  100 |      11.1817
  150 |       9.7940
  200 |       9.7687
  250 |       9.7587
  300 |       9.7489
  350 |       9.7389
  400 |       9.7292
  450 |       9.7194
  500 |       9.7096
  550 |       9.6999
  600 |       9.6903
  650 |       9.6806
  700 |       9.6709
  750 |       9.6612
  800 |       9.6517
  850 |       9.6421
  900 |       9.6325
  950 |       9.6229
 1000 |       9.6134


In [10]:
# 
data = np.array([
    # X1,   X2,    X3,   y
    [ 73.,  80.,  75., 152. ],
    [ 93.,  88.,  93., 185. ],
    [ 89.,  91.,  90., 180. ],
    [ 96.,  98., 100., 196. ],
    [ 73.,  66.,  70., 142. ]
], dtype=np.float32)

# slice data
X = data[:, :-1]    # data로부터 X1, X2, X3 값 slice
y = data[:, [-1]]    # data로부터 y 값 slice

W = tf.Variable(tf.random_normal([3, 1]))    # 정규분포를 따르는 random number
                                             # (shape=(3, 1))를 생성, W가 참조
b = tf.Variable(tf.random_normal([1]))    # 정규분포를 따르는 random number
                                          # (shape=(1,))를 생성, b가 참조 

learning_rate = 0.000001    # learning_rate를 0.000001로 설정

# hypothesis, prediction function
def predict(X):    # prediction(hypothesis) 함수 정의
    return tf.matmul(X, W) + b    # XW + b return

print("epoch | cost")    # step | cost

n_epochs = 2000    # 시행 횟수 정의
for i in range(n_epochs+1):    # 2001회(n_epochs+1) 시행
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
                # with 범위 내 variable들의 변화를 tape에 기록 (여기서는 W, b가 해당)
        cost = tf.reduce_mean((tf.square(predict(X) - y)))
                # cost function 정의 : (1/m) * ∑(i=1~m) ((XW + b)-y)^2

    # calculates the gradients of the loss
    W_grad, b_grad = tape.gradient(cost, [W, b])
                # gradient 함수가 cost function을 W, b에 대하여 미분한 값을 tuple 형태로 반환
                # 반환된 값을 W_grad, b_grad가 참조
                # tape.gradient(GradientTape.gradient) 호출 직후,
                # tape(GradientTape)에 포함된 리소스는 해제됨  
    # updates parameters (W and b)
    W.assign_sub(learning_rate * W_grad)    # W = W - learning_rate(=0.000001) * W_grad
    b.assign_sub(learning_rate * b_grad)    # b = b - learning_rate(=0.000001) * b_grad
    
    if i % 100 == 0:    # 100회마다
        # i 값(step), cost function 값 출력
        print("{:5} | {:10.4f}".format(i, cost.numpy()))

epoch | cost
    0 |  5455.5903
  100 |    31.7443
  200 |    30.9326
  300 |    30.7894
  400 |    30.6468
  500 |    30.5055
  600 |    30.3644
  700 |    30.2242
  800 |    30.0849
  900 |    29.9463
 1000 |    29.8081
 1100 |    29.6710
 1200 |    29.5348
 1300 |    29.3989
 1400 |    29.2641
 1500 |    29.1299
 1600 |    28.9961
 1700 |    28.8634
 1800 |    28.7313
 1900 |    28.5997
 2000 |    28.4689


In [11]:
W.numpy()    # W 노드에 삽입된 데이터를 출력

array([[ 1.368576 ],
       [ 2.1047728],
       [-1.4229954]], dtype=float32)

In [12]:
b.numpy()    # b 노드에 삽입된 데이터를 출력 

array([-1.1783521], dtype=float32)

In [13]:
tf.matmul(X, W) + b    # XW + b

<tf.Tensor: id=383101, shape=(5, 1), dtype=float32, numpy=
array([[160.38487],
       [178.98064],
       [184.08965],
       [194.17314],
       [138.03304]], dtype=float32)>

In [14]:
Y # labels, 실제값

[152.0, 185.0, 180.0, 196.0, 142.0]

In [15]:
predict(X).numpy() # prediction, 예측값

array([[160.38487],
       [178.98064],
       [184.08965],
       [194.17314],
       [138.03304]], dtype=float32)

In [16]:
# 새로운 데이터에 대한 예측
predict([[ 89.,  95.,  92.],[ 84.,  92.,  85.]]).numpy()

array([[189.66275],
       [186.46652]], dtype=float32)